package: "echo_server"

source_directories:
  - "./src"

main_module: "App"

dependencies:
  - name: "stdlib"
    source:
      type: "local"
      directory: "../../external/stdlib"

erlang:
  output_directory: "./_generated"
  erlang_dependencies:
    - name: "cowboy"
      source:
        type: "hex"
        version: "2.8.0"
  relx:
    release:
      name: "echo_server"
      version: "0.1.0"
      applications:
        - "cowboy"
        - "echo_server"
    dev_mode: true
