# Based on https://github.com/thomaseizinger/github-action-gitflow-release-workflow

name: "Prepare new release PR"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release. (e.g. "0.0.1")'
        required: true

jobs:
  prepare-new-release-pr:
    name: Prepare a new release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: v${{ github.event.inputs.version }}

      - name: Initialize mandatory git config
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"

      - name: Bump version
        run: |
          LAST_TAG_REV=$(git rev-list --tags --max-count=1)
          PREVIOUS_VERSION=$(git describe --tags "$LAST_TAG_REV"  | sed 's/v//')
          echo "$PREVIOUS_VERSION"
          NEW_VERSION="${{ github.event.inputs.version }}"
          echo "$NEW_VERSION"
          sed -i "0,/$PREVIOUS_VERSION/s//$NEW_VERSION/" dune-project
          sed -i "0,/$PREVIOUS_VERSION/s//$NEW_VERSION/" sesterl.opam
          sed -i "0,/$PREVIOUS_VERSION/s//$NEW_VERSION/" src/constants.ml

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md dune-project sesterl.opam src/constants.ml
          git commit --message "Prepare release v${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: Release v${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}
          body: |
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
            Merging this PR will trigger a workflow to create git tag, a GitHub release and upload any assets that are created as part of the release build.
